//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 03:05:36 PM MSK 
//


package ru.task;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for candyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="candyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Caramel"/>
 *     &lt;enumeration value="Iris"/>
 *     &lt;enumeration value="Chocolate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "candyType")
@XmlEnum
public enum CandyType {

    @XmlEnumValue("Caramel")
    CARAMEL("Caramel"),
    @XmlEnumValue("Iris")
    IRIS("Iris"),
    @XmlEnumValue("Chocolate")
    CHOCOLATE("Chocolate");
    private final String value;

    CandyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CandyType fromValue(String v) {
        for (CandyType c: CandyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
