//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 03:05:36 PM MSK 
//


package ru.task;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="candy">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ingredients" type="{http://www.ingredients.ru}ingredientsType"/>
 *                   &lt;element name="properties" type="{http://www.candy.ru}propType"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="nameCandy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="calories" use="required" type="{http://www.candy.ru}kkalType" />
 *                 &lt;attribute name="typeCandy" use="required" type="{http://www.candy.ru}candyType" />
 *                 &lt;attribute name="producer" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "candy"
})
@XmlRootElement(name = "candies")
public class Candies {

    protected List<Candies.Candy> candy;

    /**
     * Gets the value of the candy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the candy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCandy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Candies.Candy }
     * 
     * 
     */
    public List<Candies.Candy> getCandy() {
        if (candy == null) {
            candy = new ArrayList<Candies.Candy>();
        }
        return this.candy;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ingredients" type="{http://www.ingredients.ru}ingredientsType"/>
     *         &lt;element name="properties" type="{http://www.candy.ru}propType"/>
     *       &lt;/sequence>
     *       &lt;attribute name="nameCandy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="calories" use="required" type="{http://www.candy.ru}kkalType" />
     *       &lt;attribute name="typeCandy" use="required" type="{http://www.candy.ru}candyType" />
     *       &lt;attribute name="producer" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ingredients",
        "properties"
    })
    public static class Candy {

        @XmlElement(required = true)
        protected IngredientsType ingredients;
        @XmlElement(required = true)
        protected PropType properties;
        @XmlAttribute(name = "nameCandy", required = true)
        protected String nameCandy;
        @XmlAttribute(name = "calories", required = true)
        protected int calories;
        @XmlAttribute(name = "typeCandy", required = true)
        protected CandyType typeCandy;
        @XmlAttribute(name = "producer", required = true)
        protected String producer;

        /**
         * Gets the value of the ingredients property.
         * 
         * @return
         *     possible object is
         *     {@link IngredientsType }
         *     
         */
        public IngredientsType getIngredients() {
            return ingredients;
        }

        /**
         * Sets the value of the ingredients property.
         * 
         * @param value
         *     allowed object is
         *     {@link IngredientsType }
         *     
         */
        public void setIngredients(IngredientsType value) {
            this.ingredients = value;
        }

        /**
         * Gets the value of the properties property.
         * 
         * @return
         *     possible object is
         *     {@link PropType }
         *     
         */
        public PropType getProperties() {
            return properties;
        }

        /**
         * Sets the value of the properties property.
         * 
         * @param value
         *     allowed object is
         *     {@link PropType }
         *     
         */
        public void setProperties(PropType value) {
            this.properties = value;
        }

        /**
         * Gets the value of the nameCandy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameCandy() {
            return nameCandy;
        }

        /**
         * Sets the value of the nameCandy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameCandy(String value) {
            this.nameCandy = value;
        }

        /**
         * Gets the value of the calories property.
         * 
         */
        public int getCalories() {
            return calories;
        }

        /**
         * Sets the value of the calories property.
         * 
         */
        public void setCalories(int value) {
            this.calories = value;
        }

        /**
         * Gets the value of the typeCandy property.
         * 
         * @return
         *     possible object is
         *     {@link CandyType }
         *     
         */
        public CandyType getTypeCandy() {
            return typeCandy;
        }

        /**
         * Sets the value of the typeCandy property.
         * 
         * @param value
         *     allowed object is
         *     {@link CandyType }
         *     
         */
        public void setTypeCandy(CandyType value) {
            this.typeCandy = value;
        }

        /**
         * Gets the value of the producer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProducer() {
            return producer;
        }

        /**
         * Sets the value of the producer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProducer(String value) {
            this.producer = value;
        }

    }

}
