//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 03:05:36 PM MSK 
//


package ru.task;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ingredientsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ingredientsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="water" type="{http://www.ingredients.ru}mgType"/>
 *         &lt;element name="sugar" type="{http://www.ingredients.ru}mgType"/>
 *         &lt;element name="fructose" type="{http://www.ingredients.ru}mgType"/>
 *         &lt;element name="chocolate" type="{http://www.ingredients.ru}chocolateType" minOccurs="0"/>
 *         &lt;element name="vanilin" type="{http://www.ingredients.ru}mgType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ingredientsType", namespace = "http://www.ingredients.ru", propOrder = {
    "water",
    "sugar",
    "fructose",
    "chocolate",
    "vanilin"
})
public class IngredientsType {

    protected int water;
    protected int sugar;
    protected int fructose;
    protected ChocolateType chocolate;
    protected int vanilin;

    /**
     * Gets the value of the water property.
     * 
     */
    public int getWater() {
        return water;
    }

    /**
     * Sets the value of the water property.
     * 
     */
    public void setWater(int value) {
        this.water = value;
    }

    /**
     * Gets the value of the sugar property.
     * 
     */
    public int getSugar() {
        return sugar;
    }

    /**
     * Sets the value of the sugar property.
     * 
     */
    public void setSugar(int value) {
        this.sugar = value;
    }

    /**
     * Gets the value of the fructose property.
     * 
     */
    public int getFructose() {
        return fructose;
    }

    /**
     * Sets the value of the fructose property.
     * 
     */
    public void setFructose(int value) {
        this.fructose = value;
    }

    /**
     * Gets the value of the chocolate property.
     * 
     * @return
     *     possible object is
     *     {@link ChocolateType }
     *     
     */
    public ChocolateType getChocolate() {
        return chocolate;
    }

    /**
     * Sets the value of the chocolate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChocolateType }
     *     
     */
    public void setChocolate(ChocolateType value) {
        this.chocolate = value;
    }

    /**
     * Gets the value of the vanilin property.
     * 
     */
    public int getVanilin() {
        return vanilin;
    }

    /**
     * Sets the value of the vanilin property.
     * 
     */
    public void setVanilin(int value) {
        this.vanilin = value;
    }

}
